name: effective_test
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  get_it: ^7.6.8
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_preview: ^1.1.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  equatable: ^2.0.5
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
